# Site Settings
title:               "J. David Maclean"
tagline:             "I'm without spoon"
url:                 "https://jdavidmaclean.com"
baseurl:             ""
description:         "J. David Maclean > A motivated solutions-driven technical thinker with a creative history and an aptitude for tutoring. Passionate about designing systems, managing projects and communicating ideas in the online, education, design, and publishing markets."

author:
  name:              "J. David Maclean"
  email:             "j.david.maclean@gmail.com"
#  github:            
#  codepen:           
#  stackExchange:     

# Custom vars
version:             1.0
#debug:              
analytics_id:        UA-92019002-1
contentPath:         "/content" #for richmedia content

# Build settings
#sass:
#  sass_dir:          _sass
#  style:             nested #nested|compact|expanded|compressed
#  sourcemap:         true

permalink:           pretty
markdown:            kramdown
highlighter:         none
#paginate:            1000

kramdown:
  auto_ids:          true
  syntax_highlighter_opts:
    disable :        true
#  parse_block_html:  true

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-toc
# - octopress-autoprefixer
# - jekyll-paginate
# - jekyll-gist
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - _build
include:
  - _pages